### ISSUE TITLE
Swift 1.2 minor issues

### ISSUE THREAD

**Issue by hatunike** [dasdom/DDHTweaks#1]
Some issues with swift 1.2, the conversion tool gives 2 or 3 change recommendations. I might submit a pull request, but I'm still new to swift so not sure if the decisions were right.

**Comment by dasdom** [comment]
Make sure it compiles and submit a pull request. Thanks!

**Comment by chunkyguy** [comment]
I've submitted a pull request that complies the code with Swift 1.2. https://github.com/dasdom/DDHTweaks/pull/2
